# Generated by Django 2.2.5 on 2019-10-08 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0002_auto_20191007_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='difficulty',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='length',
            field=models.FloatField(default=1),
        ),
    ]
