# Generated by Django 2.2.6 on 2019-11-03 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0003_auto_20191008_1008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curriculum',
            name='body',
        ),
        migrations.AddField(
            model_name='curriculum',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='curriculum',
            name='difficulty',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='curriculum',
            name='length',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='curriculum',
            name='title',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
