# Generated by Django 2.2.6 on 2019-11-25 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0005_auto_20191104_0548'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
