# Generated by Django 2.2.6 on 2019-11-25 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0006_delete_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='curriculum',
            name='avg_rating',
        ),
        migrations.RemoveField(
            model_name='curriculum',
            name='last_modified',
        ),
        migrations.RemoveField(
            model_name='curriculum',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='avg_rating',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='last_modified',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='owner',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
