# Generated by Django 2.2.6 on 2019-11-25 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0009_auto_20191125_1506'),
        ('lesson', '0010_auto_20191125_1545'),
    ]

    operations = [
    ]
